import Header from "@/components/header/Header";
import localFont from "next/font/local";
import "./globals.css";

 
 
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
       <Header/>
       <div className="container px-3 py-3">
          {children}
       </div>
      </body>
    </html>
  );
}
