import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import localFont from "next/font/local";
import "./globals.css";
import "../font.css";
 
 
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
       <Header/>
      
          {children}
       <Footer/>
      </body>
    </html>
  );
}
